# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-23 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliothek', '0006_auto_20171211_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zotero_Buch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('admin_kaeufe', models.TextField(blank=True, default='')),
                ('titel', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('zotero_key', models.CharField(max_length=50)),
                ('jahr', models.DateField(blank=True)),
                ('sprache', models.CharField(blank=True, max_length=100)),
                ('preis_kaufen', models.SmallIntegerField(blank=True, null=True)),
                ('anzahl_kaufen', models.SmallIntegerField(blank=True, default=0)),
                ('preis_leihen', models.SmallIntegerField(blank=True, null=True)),
                ('anzahl_leihen', models.SmallIntegerField(blank=True, default=0)),
                ('preis_druck', models.SmallIntegerField(blank=True, null=True)),
                ('anzahl_druck', models.SmallIntegerField(blank=True, default=0)),
                ('preis_pdf', models.SmallIntegerField(blank=True, null=True)),
                ('ob_pdf', models.BooleanField(default=0)),
                ('preis_mobi', models.SmallIntegerField(blank=True, null=True)),
                ('ob_mobi', models.BooleanField(default=0)),
                ('preis_epub', models.SmallIntegerField(blank=True, null=True)),
                ('ob_epub', models.BooleanField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
