# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-23 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliothek', '0008_remove_zotero_buch_titel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zotero_buch',
            name='jahr',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zotero_buch',
            name='sprache',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
