# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-23 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliothek', '0009_auto_20180423_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zotero_buch',
            name='zotero_key',
        ),
    ]
