# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-23 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliothek', '0010_remove_zotero_buch_zotero_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=255)),
                ('nachname', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='zotero_buch',
            name='autor',
        ),
        migrations.AddField(
            model_name='zotero_buch',
            name='autor',
            field=models.ManyToManyField(to='Bibliothek.Autor'),
        ),
    ]
