# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-23 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliothek', '0011_auto_20180423_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zotero_buch',
            old_name='autor',
            new_name='autoren',
        ),
    ]
