# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-25 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliothek', '0013_auto_20180425_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='zotero_buch',
            name='epub',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='zotero_buch',
            name='mobi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='zotero_buch',
            name='ob_epub',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='zotero_buch',
            name='ob_mobi',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='zotero_buch',
            name='preis_epub',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zotero_buch',
            name='preis_mobi',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
