# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-26 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliothek', '0014_auto_20180425_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='vorname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
