# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-30 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliothek', '0015_auto_20180426_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kollektion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('zeit_erstellt', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bibliothek.Kollektion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='zotero_buch',
            name='kollektion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bibliothek.Kollektion'),
        ),
    ]
