# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-09 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliothek', '0016_auto_20180430_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zotero_buch',
            name='kollektion',
        ),
        migrations.AddField(
            model_name='zotero_buch',
            name='kollektion',
            field=models.ManyToManyField(to='Bibliothek.Kollektion'),
        ),
    ]
