# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-12 10:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grundgeruest', '0013_auto_20180416_1431'),
        ('Bibliothek', '0017_auto_20180509_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leihe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dauer', models.IntegerField(default=30)),
                ('datum', models.DateField(default=datetime.date(2018, 5, 12))),
                ('buch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Bibliothek.Zotero_Buch')),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grundgeruest.ScholariumProfile')),
            ],
        ),
    ]
