# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-15 16:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produkte', '0004_auto_20180327_1717'),
        ('Bibliothek', '0018_leihe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zotero_buch',
            options={'ordering': ['-zeit_erstellt'], 'verbose_name': 'Buch', 'verbose_name_plural': 'Zotero Bücher'},
        ),
        migrations.AddField(
            model_name='leihe',
            name='kauf',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Produkte.Kauf'),
        ),
        migrations.AlterField(
            model_name='leihe',
            name='datum',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
