# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-28 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliothek', '0019_auto_20180515_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leihe',
            name='datum',
        ),
        migrations.RemoveField(
            model_name='leihe',
            name='dauer',
        ),
        migrations.AddField(
            model_name='leihe',
            name='rueckkehr',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leihe',
            name='versandt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
